### ISSUE TITLE
What packages do we want to demo in most places?

### ISSUE THREAD

**Issue by karthik** [ropensci/ropensciDemos#1]
What would be our "flagship" packages to demo at most workshops/conferences so we can add it to this suggests list for this package.

Currently in my mind:
- [ ] - figshare
- [ ] - gbif/bison
- [ ] - rplos
- [ ]  - rfisheries (mostly because it's a nice simple package that provides usable data without an API key)

**Comment by sckott** [comment]
Gbif and bison don't need keys, rplos/alm dont right now, but Martin said
they are rolling out keys soon

S

**Comment by karthik** [comment]
I didn't necessarily mean that the other packages needed keys. Mostly meant that it would be nice to pick a few that represent the range of things that are possible with the rOpenSci suite without showing them too many similar things.

**Comment by sckott** [comment]
Your list looks good to me.

**Comment by cboettig** [comment]
Nice list -- good breadth & balance with a cool scientific database
(gbif/bison), literature text-mining (rplos) and data sharing repository
(rfigshare).  I guess there's merit to keeping it at just these three/four.
 But in case you were looking for more:

How about taxize_?  Seems like the kind of thing everybody could have a use
for.  One of the challenges is that we are often solving problems most
ecologists don't know they have (what's gbif? isn't text-mining just to
show my keyword is a hot topic. you want me to share _what!?_)  taxize_
makes it easier for folks to work with their own data, standardizing
species names etc.

I get the most queries about fishbase, also because I think it's intuitive
for people to imagine how to use it.  Actually I get queries because it
can't do everything you'd want it to do because FishBASE doesn't have an
API, and leaves most data out of their summary XML. (Ted, tell Pauly to wip
his team into shape on this -- they've been stringing me on for a year
about getting to this...)  While frustrating, I think it's a good step to
have reached users who can imagine the functionality they want, rather than
convincing them that they need functionality you have...

treebase will hopefully be obsolete once we have a NexML parser for R....

reml has a long way to go, but the basic pieces are there:  three commands
and you can publish a data.frame in valid EML to figshare...

On Tue, Jul 2, 2013 at 7:51 AM, Scott Chamberlain
notifications@github.comwrote:

> Your list looks good to me.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ropensci/ropensciDemos/issues/1#issuecomment-20350295
> .

## 

Carl Boettiger
UC Santa Cruz
http://carlboettiger.info/
